name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
          cache: 'yarn'

      # 3. Cache node modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 4. Install node packages
      - name: Install node packages
        run: yarn install --frozen-lockfile

      # 5. Format with Prettier
      - name: Format with Prettier
        run: yarn prettier --write .

      # 6. Check prettier
      - name: Check prettier
        run: yarn check:prettier

      # 7. Commit changes if any
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Format code with Prettier" || echo "No changes to commit"

      # 8. Check lint
      - name: Check lint
        run: yarn check:lint

      # 9. Build the project
      - name: Build
        run: yarn build

      # 10. Deploy to server
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H softkr.dev >> ~/.ssh/known_hosts
          scp -r ./public/ ubuntu@softkr.dev:/softkr/blog
